name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

  workflow_dispatch:
  schedule:
    - cron: '30 23 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run build script
        run: |
          python3 ./configure.py
          make all

      - name: Deploy
        run: ./push.sh
      
      # TODO: notification
